// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace OpenHAB.Core.Rest.Models {
    public class ItemHistoryDTO : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<HistoryDataBean>? Data { get; set; }
#nullable restore
#else
        public List<HistoryDataBean> Data { get; set; }
#endif
        /// <summary>The datapoints property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Datapoints { get; set; }
#nullable restore
#else
        public string Datapoints { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The totalrecords property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Totalrecords { get; set; }
#nullable restore
#else
        public string Totalrecords { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="ItemHistoryDTO"/> and sets the default values.
        /// </summary>
        public ItemHistoryDTO() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="ItemHistoryDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ItemHistoryDTO CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ItemHistoryDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"data", n => { Data = n.GetCollectionOfObjectValues<HistoryDataBean>(HistoryDataBean.CreateFromDiscriminatorValue)?.ToList(); } },
                {"datapoints", n => { Datapoints = n.GetStringValue(); } },
                {"name", n => { Name = n.GetStringValue(); } },
                {"totalrecords", n => { Totalrecords = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<HistoryDataBean>("data", Data);
            writer.WriteStringValue("datapoints", Datapoints);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("totalrecords", Totalrecords);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
