// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OpenHAB.Core.Rest.Models {
    public enum Rule_visibility {
        [EnumMember(Value = "VISIBLE")]
        VISIBLE,
        [EnumMember(Value = "HIDDEN")]
        HIDDEN,
        [EnumMember(Value = "EXPERT")]
        EXPERT,
    }
}
