// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OpenHAB.Core.Rest.Models {
    public enum RuleStatusInfo_status {
        [EnumMember(Value = "UNINITIALIZED")]
        UNINITIALIZED,
        [EnumMember(Value = "INITIALIZING")]
        INITIALIZING,
        [EnumMember(Value = "IDLE")]
        IDLE,
        [EnumMember(Value = "RUNNING")]
        RUNNING,
    }
}
