// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OpenHAB.Core.Rest.Models {
    public enum ThingStatusInfo_status {
        [EnumMember(Value = "UNINITIALIZED")]
        UNINITIALIZED,
        [EnumMember(Value = "INITIALIZING")]
        INITIALIZING,
        [EnumMember(Value = "UNKNOWN")]
        UNKNOWN,
        [EnumMember(Value = "ONLINE")]
        ONLINE,
        [EnumMember(Value = "OFFLINE")]
        OFFLINE,
        [EnumMember(Value = "REMOVING")]
        REMOVING,
        [EnumMember(Value = "REMOVED")]
        REMOVED,
    }
}
