<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
		<RootNamespace>openHAB.Core.Client</RootNamespace>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<UseWinUI>true</UseWinUI>
		<SupportedOSPlatformVersion>10.0.19045.0</SupportedOSPlatformVersion>
		<Platforms>x86;x64;arm64</Platforms>
	</PropertyGroup>
	<ItemGroup>
	  <Content Include="Schema\openhab-schema.json" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="CommunityToolkit.WinUI.Helpers" Version="8.2.251219" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="2.2.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
		<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers">
			<Version>10.0.301</Version>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<PRIResource Include="..\Openhab.Core\Strings\de-DE\Resources.resw">
			<Link>Strings\de-DE\Resources.resw</Link>
		</PRIResource>
		<PRIResource Include="..\Openhab.Core\Strings\en-US\Resources.resw">
			<Link>Strings\en-US\Resources.resw</Link>
		</PRIResource>
		<PRIResource Include="..\Openhab.Core\Strings\de-DE\Errors.resw">
			<Link>Strings\de-DE\Errors.resw</Link>
		</PRIResource>
		<PRIResource Include="..\Openhab.Core\Strings\en-US\Errors.resw">
			<Link>Strings\en-US\Errors.resw</Link>
		</PRIResource>
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\openHAB.Common\openHAB.Common.csproj" />
	</ItemGroup>
</Project>
