// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace OpenHAB.Core.Rest.Voice.Listenandanswer {
    /// <summary>
    /// Builds and executes requests for operations under \voice\listenandanswer
    /// </summary>
    public class ListenandanswerRequestBuilder : BaseRequestBuilder {
        /// <summary>
        /// Instantiates a new <see cref="ListenandanswerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListenandanswerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/voice/listenandanswer{?hliIds*,listeningItem*,sinkId*,sourceId*,sttId*,ttsId*,voiceId*}", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new <see cref="ListenandanswerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListenandanswerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/voice/listenandanswer{?hliIds*,listeningItem*,sinkId*,sourceId*,sttId*,ttsId*,voiceId*}", rawUrl) {
        }
        /// <summary>
        /// Executes a simple dialog sequence without keyword spotting for a given audio source.
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> PostAsync(Action<RequestConfiguration<ListenandanswerRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default) {
#nullable restore
#else
        public async Task<Stream> PostAsync(Action<RequestConfiguration<ListenandanswerRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default) {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Executes a simple dialog sequence without keyword spotting for a given audio source.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<ListenandanswerRequestBuilderPostQueryParameters>>? requestConfiguration = default) {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<ListenandanswerRequestBuilderPostQueryParameters>> requestConfiguration = default) {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="ListenandanswerRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public ListenandanswerRequestBuilder WithUrl(string rawUrl) {
            return new ListenandanswerRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Executes a simple dialog sequence without keyword spotting for a given audio source.
        /// </summary>
        public class ListenandanswerRequestBuilderPostQueryParameters {
            /// <summary>interpreter IDs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("hliIds")]
            public string[]? HliIds { get; set; }
#nullable restore
#else
            [QueryParameter("hliIds")]
            public string[] HliIds { get; set; }
#endif
            /// <summary>listening item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("listeningItem")]
            public string? ListeningItem { get; set; }
#nullable restore
#else
            [QueryParameter("listeningItem")]
            public string ListeningItem { get; set; }
#endif
            /// <summary>audio sink ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sinkId")]
            public string? SinkId { get; set; }
#nullable restore
#else
            [QueryParameter("sinkId")]
            public string SinkId { get; set; }
#endif
            /// <summary>source ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sourceId")]
            public string? SourceId { get; set; }
#nullable restore
#else
            [QueryParameter("sourceId")]
            public string SourceId { get; set; }
#endif
            /// <summary>Speech-to-Text ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sttId")]
            public string? SttId { get; set; }
#nullable restore
#else
            [QueryParameter("sttId")]
            public string SttId { get; set; }
#endif
            /// <summary>Text-to-Speech ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("ttsId")]
            public string? TtsId { get; set; }
#nullable restore
#else
            [QueryParameter("ttsId")]
            public string TtsId { get; set; }
#endif
            /// <summary>voice ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("voiceId")]
            public string? VoiceId { get; set; }
#nullable restore
#else
            [QueryParameter("voiceId")]
            public string VoiceId { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class ListenandanswerRequestBuilderPostRequestConfiguration : RequestConfiguration<ListenandanswerRequestBuilderPostQueryParameters> {
        }
    }
}
