// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using OpenHAB.Core.Rest.Items.Item.Semantic.Item;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace OpenHAB.Core.Rest.Items.Item.Semantic {
    /// <summary>
    /// Builds and executes requests for operations under \items\{itemName-id}\semantic
    /// </summary>
    public class SemanticRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the openHAB.Core.Rest.items.item.semantic.item collection</summary>
        /// <param name="position">semantic class</param>
        /// <returns>A <see cref="WithSemanticClassItemRequestBuilder"/></returns>
        public WithSemanticClassItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("semanticClass", position);
            return new WithSemanticClassItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new <see cref="SemanticRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SemanticRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/items/{itemName%2Did}/semantic", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new <see cref="SemanticRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SemanticRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/items/{itemName%2Did}/semantic", rawUrl) {
        }
    }
}
