// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using OpenHAB.Core.Rest.Items.Item.Metadata.Item;
using OpenHAB.Core.Rest.Items.Item.Metadata.Namespaces;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace OpenHAB.Core.Rest.Items.Item.Metadata {
    /// <summary>
    /// Builds and executes requests for operations under \items\{itemName-id}\metadata
    /// </summary>
    public class MetadataRequestBuilder : BaseRequestBuilder {
        /// <summary>The namespaces property</summary>
        public NamespacesRequestBuilder Namespaces { get =>
            new NamespacesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the openHAB.Core.Rest.items.item.metadata.item collection</summary>
        /// <param name="position">namespace</param>
        /// <returns>A <see cref="WithNamespaceItemRequestBuilder"/></returns>
        public WithNamespaceItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("namespace", position);
            return new WithNamespaceItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new <see cref="MetadataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MetadataRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/items/{itemName%2Did}/metadata", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new <see cref="MetadataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MetadataRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/items/{itemName%2Did}/metadata", rawUrl) {
        }
    }
}
