// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace openHAB.Core.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AudioSinkDTO
    {
        /// <summary>
        /// Initializes a new instance of the AudioSinkDTO class.
        /// </summary>
        public AudioSinkDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AudioSinkDTO class.
        /// </summary>
        public AudioSinkDTO(string id = default(string), string label = default(string))
        {
            Id = id;
            Label = label;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

    }
}
