// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace openHAB.Core.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CommandDescription
    {
        /// <summary>
        /// Initializes a new instance of the CommandDescription class.
        /// </summary>
        public CommandDescription()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CommandDescription class.
        /// </summary>
        public CommandDescription(IList<CommandOption> commandOptions = default(IList<CommandOption>))
        {
            CommandOptions = commandOptions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "commandOptions")]
        public IList<CommandOption> CommandOptions { get; set; }

    }
}
