// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace openHAB.Core.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EventOutput
    {
        /// <summary>
        /// Initializes a new instance of the EventOutput class.
        /// </summary>
        public EventOutput()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EventOutput class.
        /// </summary>
        public EventOutput(Type type = default(Type), bool? closed = default(bool?))
        {
            Type = type;
            Closed = closed;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public Type Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "closed")]
        public bool? Closed { get; set; }

    }
}
