// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace openHAB.Core.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FilterCriteriaDTO
    {
        /// <summary>
        /// Initializes a new instance of the FilterCriteriaDTO class.
        /// </summary>
        public FilterCriteriaDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FilterCriteriaDTO class.
        /// </summary>
        public FilterCriteriaDTO(string value = default(string), string name = default(string))
        {
            Value = value;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
