// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace openHAB.Core.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class GroupFunctionDTO
    {
        /// <summary>
        /// Initializes a new instance of the GroupFunctionDTO class.
        /// </summary>
        public GroupFunctionDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GroupFunctionDTO class.
        /// </summary>
        public GroupFunctionDTO(string name = default(string), IList<string> paramsProperty = default(IList<string>))
        {
            Name = name;
            ParamsProperty = paramsProperty;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "params")]
        public IList<string> ParamsProperty { get; set; }

    }
}
