// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace openHAB.Core.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class HistoryDataBean
    {
        /// <summary>
        /// Initializes a new instance of the HistoryDataBean class.
        /// </summary>
        public HistoryDataBean()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the HistoryDataBean class.
        /// </summary>
        public HistoryDataBean(long? time = default(long?), string state = default(string))
        {
            Time = time;
            State = state;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "time")]
        public long? Time { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public string State { get; set; }

    }
}
