// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace openHAB.Core.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ItemChannelLinkDTO
    {
        /// <summary>
        /// Initializes a new instance of the ItemChannelLinkDTO class.
        /// </summary>
        public ItemChannelLinkDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ItemChannelLinkDTO class.
        /// </summary>
        public ItemChannelLinkDTO(string itemName = default(string), string channelUID = default(string), IDictionary<string, object> configuration = default(IDictionary<string, object>))
        {
            ItemName = itemName;
            ChannelUID = channelUID;
            Configuration = configuration;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "itemName")]
        public string ItemName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "channelUID")]
        public string ChannelUID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "configuration")]
        public IDictionary<string, object> Configuration { get; set; }

    }
}
