// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace openHAB.Core.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MetadataDTO
    {
        /// <summary>
        /// Initializes a new instance of the MetadataDTO class.
        /// </summary>
        public MetadataDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MetadataDTO class.
        /// </summary>
        public MetadataDTO(string value = default(string), IDictionary<string, object> config = default(IDictionary<string, object>))
        {
            Value = value;
            Config = config;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "config")]
        public IDictionary<string, object> Config { get; set; }

    }
}
