// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace openHAB.Core.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ParameterOptionDTO
    {
        /// <summary>
        /// Initializes a new instance of the ParameterOptionDTO class.
        /// </summary>
        public ParameterOptionDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ParameterOptionDTO class.
        /// </summary>
        public ParameterOptionDTO(string label = default(string), string value = default(string))
        {
            Label = label;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

    }
}
