// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace openHAB.Core.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ProfileTypeDTO
    {
        /// <summary>
        /// Initializes a new instance of the ProfileTypeDTO class.
        /// </summary>
        public ProfileTypeDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProfileTypeDTO class.
        /// </summary>
        public ProfileTypeDTO(string uid = default(string), string label = default(string), string kind = default(string), IList<string> supportedItemTypes = default(IList<string>))
        {
            Uid = uid;
            Label = label;
            Kind = kind;
            SupportedItemTypes = supportedItemTypes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uid")]
        public string Uid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "kind")]
        public string Kind { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supportedItemTypes")]
        public IList<string> SupportedItemTypes { get; set; }

    }
}
