// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace openHAB.Core.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RuleStatusInfo
    {
        /// <summary>
        /// Initializes a new instance of the RuleStatusInfo class.
        /// </summary>
        public RuleStatusInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RuleStatusInfo class.
        /// </summary>
        /// <param name="status">Possible values include: 'UNINITIALIZED',
        /// 'INITIALIZING', 'IDLE', 'RUNNING'</param>
        /// <param name="statusDetail">Possible values include: 'NONE',
        /// 'HANDLER_MISSING_ERROR', 'HANDLER_INITIALIZING_ERROR',
        /// 'CONFIGURATION_ERROR', 'TEMPLATE_MISSING_ERROR', 'INVALID_RULE',
        /// 'DISABLED'</param>
        public RuleStatusInfo(string status = default(string), string statusDetail = default(string), string description = default(string))
        {
            Status = status;
            StatusDetail = statusDetail;
            Description = description;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'UNINITIALIZED',
        /// 'INITIALIZING', 'IDLE', 'RUNNING'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'NONE',
        /// 'HANDLER_MISSING_ERROR', 'HANDLER_INITIALIZING_ERROR',
        /// 'CONFIGURATION_ERROR', 'TEMPLATE_MISSING_ERROR', 'INVALID_RULE',
        /// 'DISABLED'
        /// </summary>
        [JsonProperty(PropertyName = "statusDetail")]
        public string StatusDetail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

    }
}
